version: '3.8'

services:
  tg_bot:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app

  db:
    image: postgres:16.8-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data:
