version: '3.8'

services:
  tg_bot:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5434
    ports:
      - "5434:5432"
    env_file:
      - .env

volumes:
  postgres_data:
